[2021-05-04 22:25:35,759] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: nyt_bestsellers_ETL.extract_nyt_best_sellers 2021-05-04T22:13:00.234099+00:00 [queued]>
[2021-05-04 22:25:35,907] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: nyt_bestsellers_ETL.extract_nyt_best_sellers 2021-05-04T22:13:00.234099+00:00 [queued]>
[2021-05-04 22:25:35,923] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-04 22:25:35,925] {taskinstance.py:1069} INFO - Starting attempt 1 of 4
[2021-05-04 22:25:35,928] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-04 22:25:35,971] {taskinstance.py:1089} INFO - Executing <Task(_PythonDecoratedOperator): extract_nyt_best_sellers> on 2021-05-04T22:13:00.234099+00:00
[2021-05-04 22:25:36,003] {standard_task_runner.py:52} INFO - Started process 52 to run task
[2021-05-04 22:25:36,037] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'nyt_bestsellers_ETL', 'extract_nyt_best_sellers', '2021-05-04T22:13:00.234099+00:00', '--job-id', '57', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/NYT_best_sellers_ETL_dag.py', '--cfg-path', '/tmp/tmpxsf4ugwb', '--error-file', '/tmp/tmpqky0h0yb']
[2021-05-04 22:25:36,046] {standard_task_runner.py:77} INFO - Job 57: Subtask extract_nyt_best_sellers
[2021-05-04 22:25:36,322] {logging_mixin.py:104} INFO - Running <TaskInstance: nyt_bestsellers_ETL.extract_nyt_best_sellers 2021-05-04T22:13:00.234099+00:00 [running]> on host 7ea6c36b275b
[2021-05-04 22:25:36,657] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=thomasmolloyorm@gmail.com
AIRFLOW_CTX_DAG_OWNER=Thomas
AIRFLOW_CTX_DAG_ID=nyt_bestsellers_ETL
AIRFLOW_CTX_TASK_ID=extract_nyt_best_sellers
AIRFLOW_CTX_EXECUTION_DATE=2021-05-04T22:13:00.234099+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-04T22:13:00.234099+00:00
[2021-05-04 22:25:37,776] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 233, in execute
    return_value = self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/NYT_best_sellers_ETL_dag.py", line 52, in extract_nyt_best_sellers
    raise AirflowFailException('Date or Data Point not available')
airflow.exceptions.AirflowFailException: Date or Data Point not available
[2021-05-04 22:25:37,797] {taskinstance.py:1532} INFO - Immediate failure requested. Marking task as FAILED. dag_id=nyt_bestsellers_ETL, task_id=extract_nyt_best_sellers, execution_date=20210504T221300, start_date=20210504T222535, end_date=20210504T222537
[2021-05-04 22:25:37,983] {local_task_job.py:146} INFO - Task exited with return code 1
