[2021-05-04 22:03:54,385] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: nyt_best_sellers_email.sensor 2021-05-04T21:58:47.387316+00:00 [queued]>
[2021-05-04 22:03:54,570] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: nyt_best_sellers_email.sensor 2021-05-04T21:58:47.387316+00:00 [queued]>
[2021-05-04 22:03:54,573] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-04 22:03:54,577] {taskinstance.py:1069} INFO - Starting attempt 1 of 4
[2021-05-04 22:03:54,582] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-04 22:03:54,680] {taskinstance.py:1089} INFO - Executing <Task(ExternalTaskSensor): sensor> on 2021-05-04T21:58:47.387316+00:00
[2021-05-04 22:03:54,701] {standard_task_runner.py:52} INFO - Started process 44 to run task
[2021-05-04 22:03:54,792] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'nyt_best_sellers_email', 'sensor', '2021-05-04T21:58:47.387316+00:00', '--job-id', '43', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/NYT_best_sellers_email_dag.py', '--cfg-path', '/tmp/tmpdcqqfw7n', '--error-file', '/tmp/tmptuj2nusb']
[2021-05-04 22:03:54,797] {standard_task_runner.py:77} INFO - Job 43: Subtask sensor
[2021-05-04 22:03:55,837] {logging_mixin.py:104} INFO - Running <TaskInstance: nyt_best_sellers_email.sensor 2021-05-04T21:58:47.387316+00:00 [running]> on host 7ea6c36b275b
[2021-05-04 22:03:56,773] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=thomasmolloyorm@gmail.com
AIRFLOW_CTX_DAG_OWNER=Thomas
AIRFLOW_CTX_DAG_ID=nyt_best_sellers_email
AIRFLOW_CTX_TASK_ID=sensor
AIRFLOW_CTX_EXECUTION_DATE=2021-05-04T21:58:47.387316+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-04T21:58:47.387316+00:00
[2021-05-04 22:03:56,777] {external_task.py:154} INFO - Poking for nyt_bestsellers_ETL.load_nyt_best_sellers on 2021-05-04T21:58:47.387316+00:00 ... 
[2021-05-04 22:04:56,851] {external_task.py:154} INFO - Poking for nyt_bestsellers_ETL.load_nyt_best_sellers on 2021-05-04T21:58:47.387316+00:00 ... 
[2021-05-04 22:05:56,880] {external_task.py:154} INFO - Poking for nyt_bestsellers_ETL.load_nyt_best_sellers on 2021-05-04T21:58:47.387316+00:00 ... 
[2021-05-04 22:06:56,913] {external_task.py:154} INFO - Poking for nyt_bestsellers_ETL.load_nyt_best_sellers on 2021-05-04T21:58:47.387316+00:00 ... 
[2021-05-04 22:07:56,940] {external_task.py:154} INFO - Poking for nyt_bestsellers_ETL.load_nyt_best_sellers on 2021-05-04T21:58:47.387316+00:00 ... 
[2021-05-04 22:08:56,973] {external_task.py:154} INFO - Poking for nyt_bestsellers_ETL.load_nyt_best_sellers on 2021-05-04T21:58:47.387316+00:00 ... 
[2021-05-04 22:09:57,073] {external_task.py:154} INFO - Poking for nyt_bestsellers_ETL.load_nyt_best_sellers on 2021-05-04T21:58:47.387316+00:00 ... 
[2021-05-04 22:10:57,086] {external_task.py:154} INFO - Poking for nyt_bestsellers_ETL.load_nyt_best_sellers on 2021-05-04T21:58:47.387316+00:00 ... 
[2021-05-04 22:11:57,155] {external_task.py:154} INFO - Poking for nyt_bestsellers_ETL.load_nyt_best_sellers on 2021-05-04T21:58:47.387316+00:00 ... 
[2021-05-04 22:12:27,676] {local_task_job.py:77} ERROR - Received SIGTERM. Terminating subprocesses
[2021-05-04 22:12:27,700] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 44
[2021-05-04 22:12:27,713] {taskinstance.py:1265} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-05-04 22:12:27,774] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/sensors/base.py", line 243, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1267, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-05-04 22:12:27,889] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=nyt_best_sellers_email, task_id=sensor, execution_date=20210504T215847, start_date=20210504T220354, end_date=20210504T221227
[2021-05-04 22:12:32,161] {process_utils.py:66} INFO - Process psutil.Process(pid=44, status='terminated', exitcode=1, started='22:03:53') (44) terminated with exit code 1
