[2021-05-04 19:15:28,516] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: nyt_best_sellers_email.sensor 2021-05-04T19:05:21.685388+00:00 [queued]>
[2021-05-04 19:15:28,689] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: nyt_best_sellers_email.sensor 2021-05-04T19:05:21.685388+00:00 [queued]>
[2021-05-04 19:15:28,694] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-04 19:15:28,707] {taskinstance.py:1069} INFO - Starting attempt 1 of 4
[2021-05-04 19:15:28,719] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-04 19:15:28,803] {taskinstance.py:1089} INFO - Executing <Task(ExternalTaskSensor): sensor> on 2021-05-04T19:05:21.685388+00:00
[2021-05-04 19:15:28,958] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'nyt_best_sellers_email', 'sensor', '2021-05-04T19:05:21.685388+00:00', '--job-id', '24', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/NYT_best_sellers_email_dag.py', '--cfg-path', '/tmp/tmph5wjbqbj', '--error-file', '/tmp/tmp_las06t0']
[2021-05-04 19:15:28,865] {standard_task_runner.py:52} INFO - Started process 42 to run task
[2021-05-04 19:15:28,969] {standard_task_runner.py:77} INFO - Job 24: Subtask sensor
[2021-05-04 19:15:29,620] {logging_mixin.py:104} INFO - Running <TaskInstance: nyt_best_sellers_email.sensor 2021-05-04T19:05:21.685388+00:00 [running]> on host 175e6ac31e6c
[2021-05-04 19:15:30,327] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=thomasmolloyorm@gmail.com
AIRFLOW_CTX_DAG_OWNER=Thomas
AIRFLOW_CTX_DAG_ID=nyt_best_sellers_email
AIRFLOW_CTX_TASK_ID=sensor
AIRFLOW_CTX_EXECUTION_DATE=2021-05-04T19:05:21.685388+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-04T19:05:21.685388+00:00
[2021-05-04 19:15:30,375] {external_task.py:154} INFO - Poking for nyt_bestsellers_etl.load_nyt_best_sellers on 2021-05-04T19:05:21.685388+00:00 ... 
[2021-05-04 19:16:30,572] {external_task.py:154} INFO - Poking for nyt_bestsellers_etl.load_nyt_best_sellers on 2021-05-04T19:05:21.685388+00:00 ... 
[2021-05-04 19:17:30,590] {external_task.py:154} INFO - Poking for nyt_bestsellers_etl.load_nyt_best_sellers on 2021-05-04T19:05:21.685388+00:00 ... 
[2021-05-04 19:18:30,548] {external_task.py:154} INFO - Poking for nyt_bestsellers_etl.load_nyt_best_sellers on 2021-05-04T19:05:21.685388+00:00 ... 
[2021-05-04 19:19:30,542] {external_task.py:154} INFO - Poking for nyt_bestsellers_etl.load_nyt_best_sellers on 2021-05-04T19:05:21.685388+00:00 ... 
[2021-05-04 19:20:30,558] {external_task.py:154} INFO - Poking for nyt_bestsellers_etl.load_nyt_best_sellers on 2021-05-04T19:05:21.685388+00:00 ... 
[2021-05-04 19:21:30,582] {external_task.py:154} INFO - Poking for nyt_bestsellers_etl.load_nyt_best_sellers on 2021-05-04T19:05:21.685388+00:00 ... 
[2021-05-04 19:22:30,604] {external_task.py:154} INFO - Poking for nyt_bestsellers_etl.load_nyt_best_sellers on 2021-05-04T19:05:21.685388+00:00 ... 
[2021-05-04 19:23:30,623] {external_task.py:154} INFO - Poking for nyt_bestsellers_etl.load_nyt_best_sellers on 2021-05-04T19:05:21.685388+00:00 ... 
[2021-05-04 19:24:30,672] {external_task.py:154} INFO - Poking for nyt_bestsellers_etl.load_nyt_best_sellers on 2021-05-04T19:05:21.685388+00:00 ... 
[2021-05-04 19:25:30,730] {external_task.py:154} INFO - Poking for nyt_bestsellers_etl.load_nyt_best_sellers on 2021-05-04T19:05:21.685388+00:00 ... 
[2021-05-04 19:26:30,772] {external_task.py:154} INFO - Poking for nyt_bestsellers_etl.load_nyt_best_sellers on 2021-05-04T19:05:21.685388+00:00 ... 
[2021-05-04 19:27:30,805] {external_task.py:154} INFO - Poking for nyt_bestsellers_etl.load_nyt_best_sellers on 2021-05-04T19:05:21.685388+00:00 ... 
[2021-05-04 19:28:31,004] {external_task.py:154} INFO - Poking for nyt_bestsellers_etl.load_nyt_best_sellers on 2021-05-04T19:05:21.685388+00:00 ... 
[2021-05-04 19:29:08,745] {local_task_job.py:77} ERROR - Received SIGTERM. Terminating subprocesses
[2021-05-04 19:29:09,249] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 42
[2021-05-04 19:29:09,305] {taskinstance.py:1265} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-05-04 19:29:11,149] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/sensors/base.py", line 243, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1267, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-05-04 19:29:11,605] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=nyt_best_sellers_email, task_id=sensor, execution_date=20210504T190521, start_date=20210504T191528, end_date=20210504T192911
[2021-05-04 19:29:13,312] {process_utils.py:66} INFO - Process psutil.Process(pid=42, status='terminated', exitcode=1, started='19:15:28') (42) terminated with exit code 1
