[2021-05-04 18:58:09,539] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: nyt_best_sellers_email.update_sensor 2021-05-04T18:58:05.685874+00:00 [queued]>
[2021-05-04 18:58:09,627] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: nyt_best_sellers_email.update_sensor 2021-05-04T18:58:05.685874+00:00 [queued]>
[2021-05-04 18:58:09,631] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-04 18:58:09,650] {taskinstance.py:1069} INFO - Starting attempt 1 of 4
[2021-05-04 18:58:09,703] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-04 18:58:09,786] {taskinstance.py:1089} INFO - Executing <Task(ExternalTaskSensor): update_sensor> on 2021-05-04T18:58:05.685874+00:00
[2021-05-04 18:58:09,825] {standard_task_runner.py:52} INFO - Started process 49 to run task
[2021-05-04 18:58:09,880] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'nyt_best_sellers_email', 'update_sensor', '2021-05-04T18:58:05.685874+00:00', '--job-id', '17', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/NYT_best_sellers_email_dag.py', '--cfg-path', '/tmp/tmpzynjos3u', '--error-file', '/tmp/tmpvfhcvqqg']
[2021-05-04 18:58:09,944] {standard_task_runner.py:77} INFO - Job 17: Subtask update_sensor
[2021-05-04 18:58:10,162] {logging_mixin.py:104} INFO - Running <TaskInstance: nyt_best_sellers_email.update_sensor 2021-05-04T18:58:05.685874+00:00 [running]> on host 175e6ac31e6c
[2021-05-04 18:58:10,358] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=thomasmolloyorm@gmail.com
AIRFLOW_CTX_DAG_OWNER=Thomas
AIRFLOW_CTX_DAG_ID=nyt_best_sellers_email
AIRFLOW_CTX_TASK_ID=update_sensor
AIRFLOW_CTX_EXECUTION_DATE=2021-05-04T18:58:05.685874+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-04T18:58:05.685874+00:00
[2021-05-04 18:58:10,366] {external_task.py:154} INFO - Poking for nyt_bestsellers_etl.load_nyt_best_sellers on 2021-05-04T18:58:05.685874+00:00 ... 
[2021-05-04 18:59:10,382] {external_task.py:154} INFO - Poking for nyt_bestsellers_etl.load_nyt_best_sellers on 2021-05-04T18:58:05.685874+00:00 ... 
[2021-05-04 19:00:10,416] {external_task.py:154} INFO - Poking for nyt_bestsellers_etl.load_nyt_best_sellers on 2021-05-04T18:58:05.685874+00:00 ... 
[2021-05-04 19:01:10,435] {external_task.py:154} INFO - Poking for nyt_bestsellers_etl.load_nyt_best_sellers on 2021-05-04T18:58:05.685874+00:00 ... 
[2021-05-04 19:02:10,439] {external_task.py:154} INFO - Poking for nyt_bestsellers_etl.load_nyt_best_sellers on 2021-05-04T18:58:05.685874+00:00 ... 
[2021-05-04 19:03:10,471] {external_task.py:154} INFO - Poking for nyt_bestsellers_etl.load_nyt_best_sellers on 2021-05-04T18:58:05.685874+00:00 ... 
[2021-05-04 19:04:10,634] {external_task.py:154} INFO - Poking for nyt_bestsellers_etl.load_nyt_best_sellers on 2021-05-04T18:58:05.685874+00:00 ... 
[2021-05-04 19:05:10,643] {external_task.py:154} INFO - Poking for nyt_bestsellers_etl.load_nyt_best_sellers on 2021-05-04T18:58:05.685874+00:00 ... 
[2021-05-04 19:06:10,662] {external_task.py:154} INFO - Poking for nyt_bestsellers_etl.load_nyt_best_sellers on 2021-05-04T18:58:05.685874+00:00 ... 
[2021-05-04 19:07:10,708] {external_task.py:154} INFO - Poking for nyt_bestsellers_etl.load_nyt_best_sellers on 2021-05-04T18:58:05.685874+00:00 ... 
[2021-05-04 19:08:10,737] {external_task.py:154} INFO - Poking for nyt_bestsellers_etl.load_nyt_best_sellers on 2021-05-04T18:58:05.685874+00:00 ... 
[2021-05-04 19:09:11,563] {external_task.py:154} INFO - Poking for nyt_bestsellers_etl.load_nyt_best_sellers on 2021-05-04T18:58:05.685874+00:00 ... 
[2021-05-04 19:10:11,590] {external_task.py:154} INFO - Poking for nyt_bestsellers_etl.load_nyt_best_sellers on 2021-05-04T18:58:05.685874+00:00 ... 
[2021-05-04 19:10:37,189] {local_task_job.py:77} ERROR - Received SIGTERM. Terminating subprocesses
[2021-05-04 19:10:37,389] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 49
[2021-05-04 19:10:37,421] {taskinstance.py:1265} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-05-04 19:10:38,587] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/sensors/base.py", line 243, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1267, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-05-04 19:10:41,106] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=nyt_best_sellers_email, task_id=update_sensor, execution_date=20210504T185805, start_date=20210504T185809, end_date=20210504T191041
[2021-05-04 19:10:41,277] {process_utils.py:66} INFO - Process psutil.Process(pid=49, status='terminated', exitcode=1, started='18:58:08') (49) terminated with exit code 1
