[2021-05-03 22:51:37,624] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: nyt_bestsellers_ETL.extract_nyt_best_sellers 2021-05-03T22:40:21.770303+00:00 [queued]>
[2021-05-03 22:51:38,755] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: nyt_bestsellers_ETL.extract_nyt_best_sellers 2021-05-03T22:40:21.770303+00:00 [queued]>
[2021-05-03 22:51:38,905] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-03 22:51:38,957] {taskinstance.py:1069} INFO - Starting attempt 1 of 4
[2021-05-03 22:51:38,969] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-03 22:51:39,661] {taskinstance.py:1089} INFO - Executing <Task(_PythonDecoratedOperator): extract_nyt_best_sellers> on 2021-05-03T22:40:21.770303+00:00
[2021-05-03 22:51:40,069] {standard_task_runner.py:52} INFO - Started process 43 to run task
[2021-05-03 22:51:40,698] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'nyt_bestsellers_ETL', 'extract_nyt_best_sellers', '2021-05-03T22:40:21.770303+00:00', '--job-id', '3', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/NYT_best_sellers_ETL_dag.py', '--cfg-path', '/tmp/tmp1lyxg69s', '--error-file', '/tmp/tmpy00jpnjr']
[2021-05-03 22:51:40,703] {standard_task_runner.py:77} INFO - Job 3: Subtask extract_nyt_best_sellers
[2021-05-03 22:51:42,468] {logging_mixin.py:104} INFO - Running <TaskInstance: nyt_bestsellers_ETL.extract_nyt_best_sellers 2021-05-03T22:40:21.770303+00:00 [running]> on host 131c21e8cb61
[2021-05-03 22:51:44,175] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=thomasmolloyorm@gmail.com
AIRFLOW_CTX_DAG_OWNER=Thomas
AIRFLOW_CTX_DAG_ID=nyt_bestsellers_ETL
AIRFLOW_CTX_TASK_ID=extract_nyt_best_sellers
AIRFLOW_CTX_EXECUTION_DATE=2021-05-03T22:40:21.770303+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-03T22:40:21.770303+00:00
[2021-05-03 22:51:44,286] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 233, in execute
    return_value = self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/NYT_best_sellers_ETL_dag.py", line 46, in extract_nyt_best_sellers
    date = Variable.get('next_update_date')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/variable.py", line 128, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable next_update_date does not exist'
[2021-05-03 22:51:44,424] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=nyt_bestsellers_ETL, task_id=extract_nyt_best_sellers, execution_date=20210503T224021, start_date=20210503T225137, end_date=20210503T225144
[2021-05-03 22:51:44,645] {local_task_job.py:146} INFO - Task exited with return code 1
