[2021-05-04 22:49:55,269] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: nyt_best_sellers_email.sensor 2021-05-04T22:39:24.095855+00:00 [queued]>
[2021-05-04 22:49:56,003] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: nyt_best_sellers_email.sensor 2021-05-04T22:39:24.095855+00:00 [queued]>
[2021-05-04 22:49:56,008] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-04 22:49:56,012] {taskinstance.py:1069} INFO - Starting attempt 1 of 4
[2021-05-04 22:49:56,015] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-04 22:49:56,395] {taskinstance.py:1089} INFO - Executing <Task(ExternalTaskSensor): sensor> on 2021-05-04T22:39:24.095855+00:00
[2021-05-04 22:49:56,414] {standard_task_runner.py:52} INFO - Started process 43 to run task
[2021-05-04 22:49:56,554] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'nyt_best_sellers_email', 'sensor', '2021-05-04T22:39:24.095855+00:00', '--job-id', '61', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/NYT_best_sellers_email_dag.py', '--cfg-path', '/tmp/tmpjb69wmsm', '--error-file', '/tmp/tmp59dxnu1u']
[2021-05-04 22:49:56,572] {standard_task_runner.py:77} INFO - Job 61: Subtask sensor
[2021-05-04 22:49:58,170] {logging_mixin.py:104} INFO - Running <TaskInstance: nyt_best_sellers_email.sensor 2021-05-04T22:39:24.095855+00:00 [running]> on host 7ea6c36b275b
[2021-05-04 22:49:58,399] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=thomasmolloyorm@gmail.com
AIRFLOW_CTX_DAG_OWNER=Thomas
AIRFLOW_CTX_DAG_ID=nyt_best_sellers_email
AIRFLOW_CTX_TASK_ID=sensor
AIRFLOW_CTX_EXECUTION_DATE=2021-05-04T22:39:24.095855+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-04T22:39:24.095855+00:00
[2021-05-04 22:49:58,415] {external_task.py:154} INFO - Poking for nyt_bestsellers_ETL.load_nyt_best_sellers on 2021-05-04T22:39:24.095855+00:00 ... 
[2021-05-04 22:50:58,502] {external_task.py:154} INFO - Poking for nyt_bestsellers_ETL.load_nyt_best_sellers on 2021-05-04T22:39:24.095855+00:00 ... 
[2021-05-04 22:51:58,621] {external_task.py:154} INFO - Poking for nyt_bestsellers_ETL.load_nyt_best_sellers on 2021-05-04T22:39:24.095855+00:00 ... 
[2021-05-04 22:52:58,650] {external_task.py:154} INFO - Poking for nyt_bestsellers_ETL.load_nyt_best_sellers on 2021-05-04T22:39:24.095855+00:00 ... 
[2021-05-04 22:53:58,773] {external_task.py:154} INFO - Poking for nyt_bestsellers_ETL.load_nyt_best_sellers on 2021-05-04T22:39:24.095855+00:00 ... 
[2021-05-04 22:54:58,790] {external_task.py:154} INFO - Poking for nyt_bestsellers_ETL.load_nyt_best_sellers on 2021-05-04T22:39:24.095855+00:00 ... 
[2021-05-04 22:55:58,759] {external_task.py:154} INFO - Poking for nyt_bestsellers_ETL.load_nyt_best_sellers on 2021-05-04T22:39:24.095855+00:00 ... 
[2021-05-04 22:56:58,778] {external_task.py:154} INFO - Poking for nyt_bestsellers_ETL.load_nyt_best_sellers on 2021-05-04T22:39:24.095855+00:00 ... 
[2021-05-04 22:57:59,099] {external_task.py:154} INFO - Poking for nyt_bestsellers_ETL.load_nyt_best_sellers on 2021-05-04T22:39:24.095855+00:00 ... 
[2021-05-04 22:58:59,168] {external_task.py:154} INFO - Poking for nyt_bestsellers_ETL.load_nyt_best_sellers on 2021-05-04T22:39:24.095855+00:00 ... 
[2021-05-04 22:59:59,131] {external_task.py:154} INFO - Poking for nyt_bestsellers_ETL.load_nyt_best_sellers on 2021-05-04T22:39:24.095855+00:00 ... 
[2021-05-04 23:00:59,121] {external_task.py:154} INFO - Poking for nyt_bestsellers_ETL.load_nyt_best_sellers on 2021-05-04T22:39:24.095855+00:00 ... 
[2021-05-04 23:01:22,934] {local_task_job.py:77} ERROR - Received SIGTERM. Terminating subprocesses
[2021-05-04 23:01:22,945] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 43
[2021-05-04 23:01:22,954] {taskinstance.py:1265} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-05-04 23:01:22,996] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/sensors/base.py", line 243, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1267, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-05-04 23:01:23,019] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=nyt_best_sellers_email, task_id=sensor, execution_date=20210504T223924, start_date=20210504T224955, end_date=20210504T230123
[2021-05-04 23:01:28,579] {process_utils.py:66} INFO - Process psutil.Process(pid=43, status='terminated', exitcode=1, started='22:49:55') (43) terminated with exit code 1
